name: pip - Build Lint Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: "ipod"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install openorb using conda
        run: conda install -c defaults -c conda-forge openorb --yes
      - name: Update OBSCODE.dat
        run: |
          cd $CONDA_PREFIX/share/oorb
          curl https://www.minorplanetcenter.net/iau/lists/ObsCodes.html -o ObsCodes.html
          sed -e '2d' ObsCodes.html | grep -v "<" > OBSCODE.dat
          rm -f ObsCodes.html
          cp OBSCODE.dat $CONDA_PREFIX/share/openorb/OBSCODE.dat
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PDM
        run: |
          pip install pip --upgrade
          pip install pdm
      - name: Install Testing Dependencies
        run: |
          pdm install -G test
      - name: Lint
        run: pdm run lint
      - name: Test with coverage
        run: pdm run coverage
      - name: Coverage report to coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          path-to-lcov: coverage.xml